### ISSUE TITLE
Implement 'yes' in Visual Basic

### ISSUE THREAD

**Issue by TheBinaryFox** [mubaris/yes#37]
Using Mono

**Comment by quamv** [comment]
First timer. Thank you for the project. How do I go about getting involved? I have a git account, have checked out the project into a new branch and made the change locally successfully (although I am working on Windows so I had to guess at the build command. I tried a xNix shell account but they didn't have the vbnc compiler installed). Thanks.

Also, as a purely stylistic comment, the BUILD.md has a set of examples of command lines for usage. In each case there is one example with no parameters and another with parameters. These are separated in the file, and I am used to seeing optional parameters in brackets instead of as a separate example. If there is a desire to consolidate those into single examples (e.g. "./yes [argument list]") I would be happy to do that as well.

**Comment by mubaris** [comment]
This project was started as a way to start for new comers. Appreciate your help :+1:
